### ISSUE TITLE
pi graphs update --is-secret false: don't work

### ISSUE THREAD

**Issue by ebc-2in2crc** [a-know/pi#15]
Hi. pi is a so cool tool!
But I'm in trouble...

- macOS: 10.14.5
- pi version: 1.0.3 (rev: 2cb8b0a)

`--is-secret true` work.

```
$ pi graphs update -u <my-user-id> -g <my-graph-id> --is-secret true
$ pi graphs get -u <my-user-id>
{
  "graphs": [
    {
      "id": "my-graph-id",
      "name": "my-graph",
      "unit": "count",
      "type": "int",
      "color": "shibafu",
      "timezone": "UTC",
      "purgeCacheURLs": null,
      "selfSufficient": "none",
      "isSecret": true,
      "publishOptionalData": false
    }
  ]
}
```

But, `--is-secret false` don't work.
I expected that `isSecret` would be false.
`isSecret` is still true.

```
$ pi graphs update -u <my-user-id> -g <my-graph-id> --is-secret false
$ pi graphs get -u <my-user-id>
{
  "graphs": [
    {
      "id": "my-graph-id",
      "name": "my-graph",
      "unit": "count",
      "type": "int",
      "color": "shibafu",
      "timezone": "UTC",
      "purgeCacheURLs": null,
      "selfSufficient": "none",
      "isSecret": true,
      "publishOptionalData": false
    }
  ]
}
```

How do I get `isSecret` to be false?

**Comment by a-know** [comment]
@ebc-2in2crc 
Thank you for telling me the malfunction! 😄 
The cause of this phenomenon was that I misunderstood how to specify the truth value. 😓 

It becomes `true` just by specifying the `--is-secret` flag, or `false` if this flag is not specified.


```
pi graphs update -u a-know -g test-graph --is-secret
# "isSecret":true
pi graphs update -u a-know -g test-graph
# "isSecret":false
```

It seems that it is necessary to reconsider how to specify the option. Thank you for your point! 😄

**Comment by ebc-2in2crc** [comment]
Thank you for considering this issue!
I understood how to specify `--is-secret` flag :)

BTW, if I want to specify only the `--is-secret` flag, how do I specify it?
I executed `pi graphs update` command with `-u`, `-g` and `--is-secret` flag.
I received the following message:

```
$ pi graphs update -u <my-user-id> -g <my-graph-id>
{"message":"Either name, unit, color, timezone, purgeCacheURLs, selfSufficient, isSecret or publishOptionalData must be specified.","isSuccess":false}
```

Thanks!

**Comment by a-know** [comment]
There is still a problem pointed out by you. 😞 
The idea I'm thinking now is to provide `pi` 's own option like `--is-publish`.

```
pi graphs update -u a-know -g test-graph --is-secret
# curl -X PUT https://pixe.la/v1/users/a-know/graphs/test-graph -H 'X-USER-TOKEN:thisissecret' -d '{"isSecret":true}'
pi graphs update -u a-know -g test-graph --is-publish
# curl -X PUT https://pixe.la/v1/users/a-know/graphs/test-graph -H 'X-USER-TOKEN:thisissecret' -d '{"isSecret":false}'
pi graphs update -u a-know -g test-graph -n new-name
pi graphs update -u a-know -g test-graph --is-secret
# curl -X PUT https://pixe.la/v1/users/a-know/graphs/test-graph -H 'X-USER-TOKEN:thisissecret' -d '{"name":"new-name"}'
```

🤔

**Comment by ebc-2in2crc** [comment]
I think it is a good idea to add the `--is-publish` option.  
I think it would be better to document which is used when both `--is-secret` and `--is-publish` are specified.

**Comment by a-know** [comment]
> I think it would be better to document which is used when both --is-secret and --is-publish are specified.

As you say 😉 
Along with the implementation changes, I will also make changes to the documentation. 💪

**Comment by ebc-2in2crc** [comment]
I look forward to making `pi` a more useful tool.
I close this issue.
Thank you for considering this issue!!
