### ISSUE TITLE
windows_amd64に関して

### ISSUE THREAD

**Issue by ueponx** [a-know/pi#9]
Windows版の使用させていただきました。```windows_amd64```のアーカイブなのですが、中に入っている実行ファイルの```pi```に拡張子がないので実行にはリネームが必要かなと思いましたがどうでしょうか。

**Comment by a-know** [comment]
Thank you for asking, "Is it necessary to rename something like `pi.exe` to use a binary for Windows? "
「Windows用のバイナリを利用するためには `pi.exe` などにリネームする必要があるのではないか？」というご質問、ありがとうございます！

I intended to confirm the operation on Windows, but I will check it again just in case.
Windowsでも動作確認をしたつもりだったのですが、念のため再確認しますね。


Thank you for feedback!!
フィードバックありがとうございます！！

**Comment by a-know** [comment]
@ueponx 
I confirmed. Certainly, with the v1.0.1 package, the extension has been removed and it needs to be renamed to use it.
確認しました。たしかに、v1.0.1のパッケージでは拡張子が外れており、利用するにはリネームが必要な状態でした！

It's time to just need the v1.0.2 release (#10) , so next time I want to make sure that it's properly packaged as `pi.exe`.
ちょうど v1.0.2 のリリースが必要なタイミング (#10) なので、次回のリリースではきちんと `pi.exe` としてパッケージングされるようにしたいと思います。

I don't usually use Windows and I didn't notice it without your feedback. Thank you very much! Please wait a little more until the release.
私は Windows を普段使いしておらず、フィードバックがなければ気が付きませんでした。本当にありがとうございます！リリースまでもう少しお待ち下さい。

**Comment by ueponx** [comment]
ご連絡ありがとうございました。引き続き開発頑張ってください！

**Comment by a-know** [comment]
@ueponx 
I released v1.0.2!! I think this issue is fixed by this release. Please make sure.
v1.0.2 をリリースしました！ これで直っていると思います。確認してみてください。

https://github.com/a-know/pi/releases/tag/v1.0.2

**Comment by ueponx** [comment]
確認できました。ありがとうございます！
